import type { ReactElement } from "react";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): ReactElement {
  return (
    <html lang="en">
      <body data-component="RootLayout" className="antialiased font-sans">
        {children}
      </body>
    </html>
  );
}
RootLayout.displayName = "RootLayout";
